[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["cd server && npm ci --production=false --legacy-peer-deps"]

[phases.build]
cmds = ["cd server && npm run build"]

[start]
cmd = "cd server && npm start"
