[build]
builder = "NIXPACKS"
watchPatterns = ["server/**"]

[deploy]
startCommand = "cd server && npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/health"
healthcheckTimeout = 300
